apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  labels:
    app: presence-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
    spec:
      containers:
        - name: presence-service
          image: doorkaz/presence-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb-presencia:27017"
            - name: RABBITMQ_HOST
              value: "message-broker"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /presence-service/api/v1.0.0/presence/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /presence-service/api/v1.0.0/presence/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10