apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: presence-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - presence-service.inf326.nursoft.dev
    - presence-134-199-176-197.nip.io
    secretName: presence-service-tls
  rules:
  - host: presence-134-199-176-197.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: presence-service
            port:
              number: 80
  - host: presence-service.inf326.nursoft.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: presence-service
            port:
              number: 80
