apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: presence-service-ingress
  annotations:
    cert-manager.io/issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - demo.inf326.nursoft.dev
    - presence-134-199-176-197.nip.io
    secretName: letsencrypt
  rules:
  - host: presence-134-199-176-197.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: presence-service
            port:
              number: 80
  - host: demo.inf326.nursoft.dev
    http: &demo_rules
      paths:
      - path: /presence-service
        pathType: Prefix
        backend:
          service:
            name: presence-service
            port:
              number: 8000
