services:
  presencia:
    build: .
    container_name: presence_service
    ports:
      - "5002:8000"
    volumes:
      - .:/code
    depends_on:
      - mongodb_presencia
      - rabbitmq
    networks:
      - demo_04
  tests:
    build: .
    container_name: presence_tests
    command: pytest -s -vv -W ignore::DeprecationWarning app/tests
    volumes:
      - .:/code
    depends_on:
      - presencia       
    networks:
      - demo_04
    
  mongodb_presencia:
    image: mongo:7
    container_name: presence_mongo
    ports:
      - "27017:27017"
    volumes:
      - presence_db:/data/db
    networks:
      - demo_04
  rabbitmq:
    image: rabbitmq:3-management
    container_name: presence_rabbitmq
    ports:
      - "5672:5672"   # Puerto para conexion AMQP
      - "15672:15672" # Panel web RabbitMQ
    networks:
      - demo_04

volumes:
  presence_db:

networks:
  demo_04:
    external: true